[tool.poetry]
name = "rctab_models"
version = "0.4.0"
description = "Pydantic models for the RCTab system."
authors = ["Iain-S <25081046+Iain-S@users.noreply.github.com >"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.12.5"


[tool.poetry.group.dev.dependencies]
black = "^26.1.0"
pylint = "^4.0.4"
isort = "^7.0.0"
mypy = "^1.19.1"
pymarkdownlnt = "^0.9.35"
pydocstyle = "^6.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
